# Arquivo: config.yaml

GLOBAL:
  # O servidor de produção da XP é o único que funcionou manualmente.
  SYMBOL: WINQ25
  TIMEFRAME: MT5.TIMEFRAME_M5
  MAGIC_NUMBER: 12345
  DEVIATION: 10
  LOG_LEVEL: INFO

RISK:
  # Risco máximo que você aceita perder por operação em R$ (Exemplo: R$ 50,00)
  MAX_RISK_PER_TRADE: 10.00
  
  # Valor de 1 Ponto para o ativo (Ex: R$ 0,20 para o Mini-Índice)
  POINT_VALUE: 0.30
  
  # Número máximo de contratos que o robô pode operar (Limite de segurança)
  MAX_VOLUME_LIMIT: 5

  STRATEGY:
  EMA_SHORT_PERIOD: 2    # Corrigido
  EMA_LONG_PERIOD: 5     # Corrigido
  SL_POINTS: 20          # Corrigido